/**
 * @file tkl_watchdog.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include "esp_err.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_random.h"
#include "esp_task_wdt.h"
#include "esp_pm.h"

#include "tuya_error_code.h"
#include "tuya_cloud_types.h"

#include "tkl_system.h"
#include "tkl_watchdog.h"
#include "tkl_output.h"

#define DBG_TAG "TKL_SYSTEM"
unsigned char tuya_watchdog_tread_inited = 0;
extern int esp_clk_cpu_freq(void);
extern int esp_clk_xtal_freq(void);

/**
 * @brief watchdog init
 * 
 * @param[in] cfg: watchdog config
 *
 * @return 0, init error; >0 : the actually watchdog interval 
 */
UINT32_T tkl_watchdog_init(TUYA_WDOG_BASE_CFG_T *cfg)
{
    esp_task_wdt_config_t config;

    memset(&config, 0, sizeof(config));
    config.timeout_ms = cfg->interval_ms;
    config.trigger_panic = true;
    if (ESP_OK != esp_task_wdt_init(&config)) {
        //ESP_LOGE(DBG_TAG, "%s: call esp_task_wdt_init faield", __func__);
        return OPRT_COM_ERROR;
    }
    
    return OPRT_OK;    
}


/**
 * @brief watchdog deinit
 *
 * @param[in] none
 * 
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_watchdog_deinit(VOID_T)
{
    if (ESP_OK != esp_task_wdt_deinit()) {
        //ESP_LOGE(DBG_TAG, "%s: call esp_task_wdt_deinit faield", __func__);
        return OPRT_COM_ERROR;
    }
    return OPRT_OK;
}


/**
 * @brief refresh watch dog
 * 
 * @param[in] none
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_watchdog_refresh(VOID_T)
{
    if (!tuya_watchdog_tread_inited) {
        if (ESP_OK != esp_task_wdt_add(NULL)) {
            //ESP_LOGE(DBG_TAG, "%s: call esp_task_wdt_init faield", __func__);
            return OPRT_COM_ERROR;
        }
        tuya_watchdog_tread_inited = 1;
    }

    if (ESP_OK != esp_task_wdt_reset()) {
        //ESP_LOGE(DBG_TAG, "%s: call esp_task_wdt_reset faield", __func__);
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;    
}


