/**
 * @file tkl_system.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_system.h"
#include "tuya_error_code.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "esp_random.h"
#include "esp_system.h"
// --- END: user defines and implements ---

/**
* @brief system reset
*
* @param none
*
* @return none
*/
VOID_T tkl_system_reset(VOID_T)
{
    // --- BEGIN: user implements ---
    esp_restart();
    // --- END: user implements ---
}

/**
* @brief Get system tick count
*
* @param none
*
* @return system tick count
*/
SYS_TICK_T tkl_system_get_tick_count(VOID_T)
{
    // --- BEGIN: user implements ---
    return (SYS_TICK_T)xTaskGetTickCount();
    // --- END: user implements ---
}

/**
* @brief Get system millisecond
*
* @param none
*
* @return system millisecond
*/
SYS_TIME_T tkl_system_get_millisecond(VOID_T)
{
    // --- BEGIN: user implements ---
    return (SYS_TIME_T)pdTICKS_TO_MS(tkl_system_get_tick_count());
    // --- END: user implements ---
}

/**
* @brief Get system random data
*
* @param[in] range: random from 0  to range
*
* @return random value
*/
INT_T tkl_system_get_random(UINT_T range)
{
    // --- BEGIN: user implements ---
    unsigned int trange = range;

    if (range == 0) {
        trange = 0xFF;
    }

    return (esp_random() % trange);
    // --- END: user implements ---
}

/**
* @brief Get system reset reason
*
* @param[in] describe: point to reset reason describe
*
* @return reset reason
*/
TUYA_RESET_REASON_E tkl_system_get_reset_reason(CHAR_T** describe)
{
    // --- BEGIN: user implements ---
    esp_reset_reason_t reason;

    reason = esp_reset_reason();
    switch (reason) {
    case ESP_RST_POWERON:
        return TUYA_RESET_REASON_POWERON;
    case ESP_RST_EXT:
        return TUYA_RESET_REASON_EXTERNAL;
    case ESP_RST_SW:
        return TUYA_RESET_REASON_SOFTWARE;
    case ESP_RST_PANIC:
        return TUYA_RESET_REASON_FAULT;
    case ESP_RST_INT_WDT:
        return TUYA_RESET_REASON_SW_WDOG;
    case ESP_RST_TASK_WDT:
        return TUYA_RESET_REASON_SW_WDOG;
    case ESP_RST_WDT:
        return TUYA_RESET_REASON_SW_WDOG;
    case ESP_RST_DEEPSLEEP:
        return TUYA_RESET_REASON_DEEPSLEEP;
    case ESP_RST_BROWNOUT:
        return TUYA_RESET_REASON_BROWNOUT;
    case ESP_RST_SDIO:
        return TUYA_RESET_REASON_EXTERNAL;
    default:
        return TUYA_RESET_REASON_UNKNOWN;
    }
    
    return TUYA_RESET_REASON_UNSUPPORT;
    // --- END: user implements ---
}

/**
* @brief  system sleep
*
* @param[in] describe: num ms
*
* @return none
*/
VOID_T tkl_system_sleep(UINT_T num_ms)
{
    // --- BEGIN: user implements ---
    TickType_t xTicksToDelay;
    xTicksToDelay = pdMS_TO_TICKS(num_ms);
    vTaskDelay(xTicksToDelay);
    // --- END: user implements ---
}

/**
* @brief system delay
*
* @param[in] msTime: time in MS
*
* @note This API is used for system sleep.
*
* @return VOID
*/
VOID_T tkl_system_delay(UINT_T num_ms)
{
    // --- BEGIN: user implements ---
    tkl_system_sleep(num_ms);
    // --- END: user implements ---
}

/**
* @brief get system cpu info
*
* @param[in] cpu_ary: info of cpus
* @param[in] cpu_cnt: num of cpu
* @note This API is used for system cpu info get.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/

OPERATE_RET tkl_system_get_cpu_info(TUYA_CPU_INFO_T **cpu_ary, INT_T *cpu_cnt)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

