/**
 * @file tkl_network.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */
#include "tkl_network.h"
#include "tuya_error_code.h"
#include "tkl_system.h"
#include "tkl_output.h"
#include <assert.h>

#include "lwip/err.h"
#include "lwip/sockets.h"
#include "lwip/dns.h"
#include "lwip/netdb.h"
#include "lwip/inet.h"


typedef struct NETWORK_ERRNO_TRANS {
    int sys_err;
    int priv_err;
} NETWORK_ERRNO_TRANS_S;

#define UNW_TO_SYS_FD_SET(fds)  ((fd_set*)fds)

const NETWORK_ERRNO_TRANS_S TKL_ERRNOrans[] = {
    {EINTR, EINTR},
    {EBADF, EBADF},
    {EAGAIN, EAGAIN},
    {EFAULT, EFAULT},
    {EBUSY, EBUSY},
    {EINVAL, EINVAL},
    {ENFILE, ENFILE},
    {EMFILE, EMFILE},
    {ENOSPC, ENOSPC},
    {EPIPE, EPIPE},
    {EWOULDBLOCK, EWOULDBLOCK},
    {ENOTSOCK, ENOTSOCK},
    {ENOPROTOOPT, ENOPROTOOPT},
    {EADDRINUSE, EADDRINUSE},
    {EADDRNOTAVAIL, EADDRNOTAVAIL},
    {ENETDOWN, ENETDOWN},
    {ENETUNREACH, ENETUNREACH},
    {ENETRESET, ENETRESET},
    {ECONNRESET, ECONNRESET},
    {ENOBUFS, ENOBUFS},
    {EISCONN, EISCONN},
    {ENOTCONN, ENOTCONN},
    {ETIMEDOUT, ETIMEDOUT},
    {ECONNREFUSED, ECONNREFUSED},
    {EHOSTDOWN, EHOSTDOWN},
    {EHOSTUNREACH, EHOSTUNREACH},
    {ENOMEM, ENOMEM},
    {EMSGSIZE, EMSGSIZE}
};

/**
* @brief Get error code of network
*
* @param void
*
* @note This API is used for getting error code of network.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_get_errno(void)
{
    int i = 0;

    int sys_err = errno;

    for (i = 0; i < (int)sizeof(TKL_ERRNOrans) / sizeof(TKL_ERRNOrans[0]); i++) {
        if (TKL_ERRNOrans[i].sys_err == sys_err) {
            return TKL_ERRNOrans[i].priv_err;
        }
    }
    return -100 - sys_err;
}

/**
* @brief Add file descriptor to set
*
* @param[in] fd: file descriptor
* @param[in] fds: set of file descriptor
*
* @note This API is used to add file descriptor to set.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_fd_set(CONST INT_T fd, TUYA_FD_SET_T* fds)
{
    if ((fd < 0) || (fds == NULL)) {
        return -3000 + fd;
    }
    FD_SET(fd, UNW_TO_SYS_FD_SET(fds));
    return OPRT_OK;
}

/**
* @brief Clear file descriptor from set
*
* @param[in] fd: file descriptor
* @param[in] fds: set of file descriptor
*
* @note This API is used to clear file descriptor from set.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_fd_clear(CONST INT_T fd, TUYA_FD_SET_T* fds)
{
    if ((fd < 0) || (fds == NULL)) {
        return -3000 + fd;
    }

    FD_CLR(fd, UNW_TO_SYS_FD_SET(fds));

    return OPRT_OK;
}

/**
* @brief Check file descriptor is in set
*
* @param[in] fd: file descriptor
* @param[in] fds: set of file descriptor
*
* @note This API is used to check the file descriptor is in set.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_fd_isset(CONST INT_T fd, TUYA_FD_SET_T* fds)
{
    if ((fd < 0) || (fds == NULL)) {
        return -3000 + fd;
    }
    return FD_ISSET(fd, UNW_TO_SYS_FD_SET(fds));
}


/**
* @brief Clear all file descriptor in set
*
* @param[in] fds: set of file descriptor
*
* @note This API is used to clear all file descriptor in set.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
INT_T tkl_net_fd_zero(TUYA_FD_SET_T *fds)
{
    if (fds == NULL) {
        return 0xFFFFFFFF;
    }

    FD_ZERO(UNW_TO_SYS_FD_SET(fds));

    return OPRT_OK;
}

/**
* @brief Get available file descriptors
*
* @param[in] maxfd: max count of file descriptor
* @param[out] readfds: a set of readalbe file descriptor
* @param[out] writefds: a set of writable file descriptor
* @param[out] errorfds: a set of except file descriptor
* @param[in] ms_timeout: time out
*
* @note This API is used to get available file descriptors.
*
* @return the count of available file descriptors.
*/
INT_T tkl_net_select(const int maxfd, TUYA_FD_SET_T *readfds, TUYA_FD_SET_T *writefds, TUYA_FD_SET_T *errorfds,
                             const unsigned int ms_timeout)
{
    if (maxfd <= 0) {
        return -3000 + maxfd;
    }

    struct timeval *tmp = NULL;
    struct timeval timeout = {ms_timeout / 1000, (ms_timeout % 1000) * 1000};
    if (0 != ms_timeout) {
        tmp = &timeout;
    } else {
        tmp = NULL;
    }
    return select(maxfd, UNW_TO_SYS_FD_SET(readfds), UNW_TO_SYS_FD_SET(writefds), UNW_TO_SYS_FD_SET(errorfds), tmp);
}

/**
* @brief Get no block file descriptors
*
* @param[in] fd: file descriptor
*
* @note This API is used to get no block file descriptors.
*
* @return the count of no block file descriptors.
*/
INT_T tkl_net_get_nonblock(const int fd)
{
    if (fd < 0) {
        return -3000 + fd;
    }


    if ((fcntl(fd, F_GETFL, 0) & O_NONBLOCK) != O_NONBLOCK) {
        return 0;
    }

    if (errno == EAGAIN || errno == EWOULDBLOCK) {
        return 1;
    }

    return 0 ;
}

/**
* @brief Set block flag for file descriptors
*
* @param[in] fd: file descriptor
* @param[in] block: block flag
*
* @note This API is used to set block flag for file descriptors.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET  tkl_net_set_block(const int fd, const bool_t block)
{

    return 0;
#if 0
    if (fd < 0) {
        return -3000 + fd;
    }

    int flags = fcntl(fd, F_GETFL, 0);
    if (block) {
        flags &= (~O_NONBLOCK);
    } else {
        flags |= O_NONBLOCK;
    }

    if (fcntl(fd, F_SETFL, flags) < 0) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
#endif
}

/**
* @brief Close file descriptors
*
* @param[in] fd: file descriptor
*
* @note This API is used to close file descriptors.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_close(const int fd)
{
    if (fd < 0) {
        return -3000 + fd;
    }
    return close(fd);
}

/**
* @brief Shutdown file descriptors
*
* @param[in] fd: file descriptor
* @param[in] how: shutdown type
*
* @note This API is used to shutdown file descriptors.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_shutdown(const int fd, const int how)
{
    if (fd < 0) {
        return -3000 + fd;
    }

    return shutdown(fd, how);
}

/**
* @brief Create a tcp/udp socket
*
* @param[in] type: protocol type, tcp or udp
*
* @note This API is used for creating a tcp/udp socket.
*
* @return file descriptor
*/
INT_T tkl_net_socket_create(CONST TUYA_PROTOCOL_TYPE_E type)
{
    int fd = -1;
    
    switch (type) {
    case PROTOCOL_TCP:
        fd = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
        break;
    case PROTOCOL_UDP:
        fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
        break;
    case PROTOCOL_RAW:
        fd = socket(AF_INET, SOCK_RAW, IPPROTO_ICMP);
        break;
    default:
        printf("err unsupport tkl_net_socket_create type(%d), fd(%d)!\r\n",type, fd);
        break;
    }

    return fd;
}


/**
* @brief Connect to network
*
* @param[in] fd: file descriptor
* @param[in] addr: address information of server
* @param[in] port: port information of server
*
* @note This API is used for connecting to network.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_connect(const int fd, const TUYA_IP_ADDR_T addr, const unsigned short port)
{
    if (fd < 0) {
        return -3000 + fd;
    }

    struct sockaddr_in sock_addr;
    unsigned short tmp_port = port;
    TUYA_IP_ADDR_T tmp_addr = addr;

    sock_addr.sin_family = AF_INET;
    sock_addr.sin_port = htons(tmp_port);
    sock_addr.sin_addr.s_addr = htonl(tmp_addr);

    return connect(fd, (struct sockaddr *)&sock_addr, sizeof(struct sockaddr_in));
}

/**
* @brief Connect to network with raw data
*
* @param[in] fd: file descriptor
* @param[in] p_socket: raw socket data
* @param[in] len: data lenth
*
* @note This API is used for connecting to network with raw data.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_connect_raw(const int fd, void *p_socket_addr, const int len)
{
    if (fd < 0) {
        return -3000 + fd;
    }
    return connect(fd, (struct sockaddr *)p_socket_addr, len);
}

/**
* @brief Bind to network
*
* @param[in] fd: file descriptor
* @param[in] addr: address information of server
* @param[in] port: port information of server
*
* @note This API is used for binding to network.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_bind(const int fd, const TUYA_IP_ADDR_T addr, const unsigned short port)
{
    if (fd < 0) {
        return -3000 + fd;
    }

    unsigned short tmp_port = port;
    TUYA_IP_ADDR_T tmp_addr = addr;

    struct sockaddr_in sock_addr;
    sock_addr.sin_family = AF_INET;
    sock_addr.sin_port = htons(tmp_port);
    sock_addr.sin_addr.s_addr = htonl(tmp_addr);

    return bind(fd, (struct sockaddr *)&sock_addr, sizeof(struct sockaddr_in));
}

/**
* @brief Listen to network
*
* @param[in] fd: file descriptor
* @param[in] backlog: max count of backlog connection
*
* @note This API is used for listening to network.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_listen(const int fd, const int backlog)
{
    if (fd < 0) {
        return -3000 + fd;
    }
    return listen(fd, backlog);
}

/**
* @brief Listen to network
*
* @param[in] fd: file descriptor
* @param[out] addr: the accept ip addr
* @param[out] port: the accept port number
*
* @note This API is used for listening to network.
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_accept(const int fd, TUYA_IP_ADDR_T *addr, unsigned short *port)
{
    if (fd < 0) {
        return -3000 + fd;
    }

    struct sockaddr_in sock_addr;
    socklen_t len = sizeof(struct sockaddr_in);
    int cfd = accept(fd, (struct sockaddr *)&sock_addr, &len);
    if (cfd < 0) {
        return OPRT_COM_ERROR;
    }

    if (addr) {
        *addr = ntohl((sock_addr.sin_addr.s_addr));
    }

    if (port) {
        *port = ntohs((sock_addr.sin_port));
    }

    return cfd;
}

/**
* @brief Send data to network
*
* @param[in] fd: file descriptor
* @param[in] buf: send data buffer
* @param[in] nbytes: buffer lenth
*
* @note This API is used for sending data to network
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_send(const int fd, const void *buf, const unsigned int nbytes)
{
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }
    return send(fd, buf, nbytes, 0);
}

/**
* @brief Send data to specified server
*
* @param[in] fd: file descriptor
* @param[in] buf: send data buffer
* @param[in] nbytes: buffer lenth
* @param[in] addr: address information of server
* @param[in] port: port information of server
*
* @note This API is used for sending data to network
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_send_to(const int fd, const void *buf, const unsigned int nbytes, \
                              const TUYA_IP_ADDR_T addr, const unsigned short port)
{
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }

    unsigned short tmp_port = port;
    TUYA_IP_ADDR_T tmp_addr = addr;

    struct sockaddr_in sock_addr;
    sock_addr.sin_family = AF_INET;
    sock_addr.sin_port = htons(tmp_port);
    sock_addr.sin_addr.s_addr = htonl(tmp_addr);
    // return -1;
    return sendto(fd, buf, nbytes, 0, (struct sockaddr *)&sock_addr, sizeof(sock_addr));
}

/**
* @brief Receive data from network
*
* @param[in] fd: file descriptor
* @param[in] buf: receive data buffer
* @param[in] nbytes: buffer lenth
*
* @note This API is used for receiving data from network
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_recv(const int fd, void *buf, const unsigned int nbytes)
{
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }
    int flags = fcntl(fd, F_GETFL, 0);

    int noblock = flags & O_NONBLOCK;

    if (!noblock) {
        fd_set set;
        FD_ZERO(&set);
        FD_SET(fd, &set);
        if (select(fd + 1, &set, NULL, NULL, NULL) < 0) {
            return -1;
        }
    }

    return recv(fd, buf, nbytes, 0);
}

/**
* @brief Receive data from network with need size
*
* @param[in] fd: file descriptor
* @param[in] buf: receive data buffer
* @param[in] nbytes: buffer lenth
* @param[in] nd_size: the need size
*
* @note This API is used for receiving data from network with need size
*
* @return >0 on success. Others on error
*/
INT_T tkl_net_recv_nd_size(const int fd, \
                                   void *buf, \
                                   const unsigned int buf_size, \
                                   const unsigned int nd_size)
{
    if ((fd < 0) || (NULL == buf) || (buf_size == 0) || \
            (nd_size == 0) || (buf_size < nd_size)) {
        return -3000 + fd;
    }

    unsigned int rd_size = 0;
    int ret = 0;

    while (rd_size < nd_size) {
        ret = recv(fd, ((uint8_t *)buf + rd_size), nd_size - rd_size, 0);
        if (ret <= 0) {
            TUYA_ERRNO err = tkl_net_get_errno();
            if (EWOULDBLOCK == err || \
                    EINTR == err || \
                    EAGAIN == err) {
                tkl_system_sleep(10);
                continue;
            }

            break;
        }

        rd_size += ret;
    }

    if (rd_size < nd_size) {
        return -2;
    }

    return rd_size;
}

/**
* @brief Receive data from specified server
*
* @param[in] fd: file descriptor
* @param[in] buf: receive data buffer
* @param[in] nbytes: buffer lenth
* @param[in] addr: address information of server
* @param[in] port: port information of server
*
* @note This API is used for receiving data from specified server
*
* @return 0 on success. Others on error, please refer to the error no of the target system
*/
TUYA_ERRNO tkl_net_recvfrom(const int fd, \
                               void *buf, \
                               const unsigned int nbytes, \
                               TUYA_IP_ADDR_T *addr, \
                               unsigned short *port)
{
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }

    struct sockaddr_in sock_addr;
    socklen_t addr_len = sizeof(struct sockaddr_in);
    int ret = recvfrom(fd, buf, nbytes, 0, (struct sockaddr *)&sock_addr, &addr_len);
    if (ret <= 0) {
        return ret;
    }

    if (addr) {
        *addr = ntohl(sock_addr.sin_addr.s_addr);
    }

    if (port) {
        *port = ntohs(sock_addr.sin_port);
    }

    return ret;
}

/**
* @brief Get address information by domain
*
* @param[in] domain: domain information
* @param[in] addr: address information
*
* @note This API is used for getting address information by domain.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_gethostbyname(CONST CHAR_T *domain, TUYA_IP_ADDR_T *addr)
{
    if ((domain == NULL) || (addr == NULL)) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    struct hostent *h = NULL;
    if ((h = gethostbyname(domain)) == NULL) {
        return OPRT_COM_ERROR;
    }

    *addr = ntohl(((struct in_addr *)(h->h_addr_list[0]))->s_addr);

    return OPRT_OK;
}

/**
* @brief Bind to network with specified ip
*
* @param[in] fd: file descriptor
* @param[in] ip: ip address
*
* @note This API is used for binding to network with specified ip.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_socket_bind(const int fd, const char *ip)
{
    if (NULL == ip) {
        return -3000;
    }

    struct sockaddr_in addr_client   = {0};
    addr_client.sin_family   = AF_INET;
    addr_client.sin_addr.s_addr      = inet_addr(ip);
    addr_client.sin_port     = 0;    /// 0 表示由系统自动分配端口号

    if (0 != bind(fd, (struct sockaddr *)&addr_client, sizeof(addr_client))) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
}

/**
* @brief Set socket fd close mode
*
* @param[in] fd: file descriptor
*
* @note This API is used for setting socket fd close mode, the socket fd will not be closed in child processes generated by fork calls.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_set_cloexec(IN CONST INT_T fd)
{
    return OPRT_OK;
}

/**
* @brief Get ip address by socket fd
*
* @param[in] fd: file descriptor
* @param[out] addr: ip address
*
* @note This API is used for getting ip address by socket fd.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_get_socket_ip(CONST INT_T fd, TUYA_IP_ADDR_T *addr)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
* @brief Change ip string to address
*
* @param[in] ip_str: ip string
*
* @note This API is used to change ip string to address.
*
* @return ip address
*/
TUYA_IP_ADDR_T tkl_net_str2addr(const char *ip)
{
    if (ip == NULL) {
        return 0xFFFFFFFF;
    }

    TUYA_IP_ADDR_T addr1 = inet_addr((char *)ip);
    TUYA_IP_ADDR_T addr2 = ntohl(addr1);

    return addr2;
}

/**
* @brief Change ip address to string
*
* @param[in] ipaddr: ip address
*
* @note This API is used to change ip address(in host byte order) to string(in IPv4 numbers-and-dots(xx.xx.xx.xx) notion).
*
* @return ip string
*/
CHAR_T* tkl_net_addr2str(CONST TUYA_IP_ADDR_T ipaddr)
{
#if defined(ENABLE_LWIP) && (ENABLE_LWIP == 1)
    unsigned int addr = lwip_htonl(ipaddr);
    return ip_ntoa((ip_addr_t *) &addr);
#else
    static CHAR_T str[10];

    utoa(ipaddr, str, 10);

    return str;
#endif

}

/**
* @brief Set socket options
*
* @param[in] fd: file descriptor
* @param[in] level: setting level
* @param[in] optname: the name of the option
* @param[in] optval: the value of option
* @param[in] optlen: the length of the option value
*
* @note This API is used for setting socket options.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_setsockopt(CONST INT_T fd, CONST TUYA_OPT_LEVEL level, CONST TUYA_OPT_NAME optname, CONST VOID_T *optval, CONST INT_T optlen)
{
    int ret = 0;

    ret |= setsockopt(fd, level, optname, optval, optlen);
    return ret;
}

/**
* @brief Get socket options
*
* @param[in] fd: file descriptor
* @param[in] level: getting level
* @param[in] optname: the name of the option
* @param[out] optval: the value of option
* @param[out] optlen: the length of the option value
*
* @note This API is used for getting socket options.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_getsockopt(CONST INT_T fd, CONST TUYA_OPT_LEVEL level, CONST TUYA_OPT_NAME optname, VOID_T *optval, INT_T *optlen)
{
    int ret = 0;
    ret = getsockopt(fd, level, optname, optval, (UINT_T *)optlen);

    return ret;
}

/**
* @brief Set timeout option of socket fd
*
* @param[in] fd: file descriptor
* @param[in] ms_timeout: timeout in ms
* @param[in] type: transfer type, receive or send
*
* @note This API is used for setting timeout option of socket fd.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_set_timeout(IN CONST INT_T fd,IN CONST INT_T ms_timeout,
                    IN CONST TUYA_TRANS_TYPE_E type)
{
    struct timeval timeout = {ms_timeout/1000, (ms_timeout%1000)*1000};
    INT_T optname = ((type == TRANS_RECV) ? SO_RCVTIMEO:SO_SNDTIMEO);

    if(0 != tkl_net_setsockopt(fd, SOL_SOCKET, optname, (CONST CHAR_T *)&timeout, sizeof(timeout))) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
}

/**
* @brief Set buffer_size option of socket fd
*
* @param[in] fd: file descriptor
* @param[in] buf_size: buffer size in byte
* @param[in] type: transfer type, receive or send
*
* @note This API is used for setting buffer_size option of socket fd.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_set_bufsize(IN CONST INT_T fd,IN CONST INT_T buf_size,
                    IN CONST TUYA_TRANS_TYPE_E type)
{
    INT_T size = buf_size;
    INT_T optname = ((type == TRANS_RECV) ? SO_RCVBUF:SO_SNDBUF);

    if(0 != tkl_net_setsockopt(fd, SOL_SOCKET, optname, (CONST CHAR_T *)&size, sizeof(size))) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
}

/**
* @brief Enable reuse option of socket fd
*
* @param[in] fd: file descriptor
*
* @note This API is used to enable reuse option of socket fd.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_set_reuse(IN CONST INT_T fd)
{
    INT_T flag = 1;
    if(0 != tkl_net_setsockopt(fd,SOL_SOCKET,SO_REUSEADDR,(CONST CHAR_T*)&flag,sizeof(int))) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
}

/**
* @brief Disable nagle option of socket fd
*
* @param[in] fd: file descriptor
*
* @note This API is used to disable nagle option of socket fd.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_disable_nagle(IN CONST INT_T fd)
{
    INT_T flag = 1;
    if(0 != tkl_net_setsockopt(fd,IPPROTO_TCP,TCP_NODELAY,(CONST CHAR_T*)&flag,sizeof(int))) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
}

/**
* @brief Enable broadcast option of socket fd
*
* @param[in] fd: file descriptor
*
* @note This API is used to enable broadcast option of socket fd.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_set_broadcast(IN CONST INT_T fd)
{
        INT_T flag = 1;
    if(0 != tkl_net_setsockopt(fd,SOL_SOCKET,SO_BROADCAST,(CONST CHAR_T*)&flag,sizeof(int))) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
}

/**
* @brief Set keepalive option of socket fd to monitor the connection
*
* @param[in] fd: file descriptor
* @param[in] alive: keepalive option, enable or disable option
* @param[in] idle: keep idle option, if the connection has no data exchange with the idle time(in seconds), start probe.
* @param[in] intr: keep interval option, the probe time interval.
* @param[in] cnt: keep count option, probe count.
*
* @note This API is used to set keepalive option of socket fd to monitor the connection.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_set_keepalive(IN INT_T fd,IN CONST BOOL_T alive,
                              IN CONST UINT_T idle,IN CONST UINT_T intr,
                              IN CONST UINT_T cnt)
{
    INT_T ret = 0;
    INT_T keepalive = alive;
    INT_T keepidle = idle;
    INT_T keepinterval = intr;
    INT_T keepcount = cnt;

    ret |= tkl_net_setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (void *)&keepalive , sizeof(keepalive));
    ret |= tkl_net_setsockopt(fd, IPPROTO_TCP, TCP_KEEPIDLE, (void*)&keepidle , sizeof(keepidle));
    ret |= tkl_net_setsockopt(fd, IPPROTO_TCP, TCP_KEEPINTVL, (void *)&keepinterval , sizeof(keepinterval));
    ret |= tkl_net_setsockopt(fd, IPPROTO_TCP, TCP_KEEPCNT, (void *)&keepcount , sizeof(keepcount));
    if(0 != ret) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
}

/**
* @brief Get name of connected peer socket
*
* @param[in] fd: file descriptor
* @param[out] addr: ip address
* @param[out] port: port information
*
* @note This API is used to Get the name of connected peer socket.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_getpeername(INT_T fd, TUYA_IP_ADDR_T *addr, UINT16_T *port)
{
    return OPRT_NOT_SUPPORTED;
}

/**
* @brief Get socket name
*
* @param[in] fd: file descriptor
* @param[out] addr: ip address
* @param[out] port: port information
*
* @note This API is used to Get the current name for the specified socket
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_getsockname(INT_T fd, TUYA_IP_ADDR_T *addr, UINT16_T *port)
{
    return OPRT_NOT_SUPPORTED;
}

/**
* @brief Set the system hostname
*
* @param[in] hostname: hostname to set
*
* @note This API is used to set the system hostname.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_net_sethostname(CONST CHAR_T *hostname)
{
    return OPRT_NOT_SUPPORTED;
}